# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

font_family CaskaydiaCove Nerd Font Mono
font_size 12

background_opacity 0.9

confirm_os_window_close 0

enabled_layouts splits

map kitty_mod+h neighboring_window left
map kitty_mod+j neighboring_window bottom
map kitty_mod+k neighboring_window top
map kitty_mod+l neighboring_window right

map kitty_mod+2 launch --location=hsplit --cwd=current
map kitty_mod+5 launch --location=vsplit --cwd=current
